--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/AntiCores/EasyHomes
branches:
- master
projects:
  EasyHomes:
    path: ""
    icon: meta/EasyHomes.png
    libs:
      - src: jojoe77777/FormAPI/FormAPI_virion
        version: ^1.3.0
...
