--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/AntiCores/EasyHomes
branches:
- master
projects:
  EasyHomes:
    path: ""
    icon: meta/EasyHomes.png
    libs:
      - src: "https://poggit.pmmp.io/r/45730/FormAPI_virion_dev-1.phar"
...
